In [1]:
import numpy as np

1. Attributes of Arrays

In [4]:
np.random.seed(0)

x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [5]:
print("x3 ndim: ", x3.ndim)
print("x3 ndim: ", x3.shape)
print("x3 ndim: ", x3.size)

x3 ndim:  3
x3 ndim:  (3, 4, 5)
x3 ndim:  60


In [6]:
print("Data Type of the array : ", x3.dtype)

Data Type of the array :  int32


In [8]:
print("Size of arrays elements each in bytes : ", x3.itemsize)
print("Size of array in bytes : ", x3.nbytes)

Size of arrays elements each in bytes :  4
Size of array in bytes :  240


<h1> Array indexing </h1>

In [9]:
x1

array([5, 0, 3, 3, 7, 9])

In [40]:
x1[0], x1[-1] 

(5, 9)

# Array Slicing  format: x[start:stop:step]

In [39]:
x1[0:3],x1[0:], x1[:5], x1[0:1:2]

(array([5, 0, 3]),
 array([5, 0, 3, 3, 7, 9]),
 array([5, 0, 3, 3, 7]),
 array([5]))

In [41]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [46]:
x2[:1, :2], x2[:2,:2]

(array([[3, 5]]),
 array([[3, 5],
        [7, 6]]))

In [49]:
x2[:,2] # 3rd column

array([2, 8, 7])

## Subarrays as no-copy views

In [50]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [52]:
x2_sub = x2[:2,:2]
x2_sub

array([[3, 5],
       [7, 6]])

In [53]:
x2_sub[0,0] = 12
x2_sub

array([[12,  5],
       [ 7,  6]])

In [54]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Creating copies of Array

In [55]:
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[12,  5],
       [ 7,  6]])

In [56]:
x2_sub_copy[0,0] = 24
x2_sub_copy

array([[24,  5],
       [ 7,  6]])

In [57]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Reshaping Arrays (size of initial array must equal tsize of target array)

In [59]:
line = np.arange(1,10)
line

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
grid = line.copy().reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array concatenation and Splitting

In [63]:
x = np.array([1,2,3])
y  = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [66]:
z  = np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
grid1 = np.zeros((3,3),dtype=int)
grid1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
grid2 = np.ones((3,3),dtype=int)
grid2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [75]:
np.concatenate([grid1,grid2],axis=0) # verticall concatenation

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [76]:
np.concatenate([grid1,grid2],axis=1) # Horizontal concatenation

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [78]:
np.vstack([grid1,grid2])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [80]:
np.hstack([grid1,grid2])

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

# Splitting of arrays

In [85]:
x = [1,2,3,4,5,6,7,8,9,0]
x1, x2, x3, x4 = np.split(x , [2,5,8])
x1, x2, x3, x4

(array([1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([9, 0]))

In [86]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
upper, lower = np.vsplit(grid, [2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [90]:
upper, lower = np.hsplit(grid, [2])
upper

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])