In [10]:
import numpy as np

# SUM of Elements using numpy UFuncs

In [4]:
L = np.random.random(100)

In [5]:
%timeit sum(L)

9.25 µs ± 78.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
%timeit np.sum(L)

3.38 µs ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
big_array = np.random.random(1000000)

In [9]:
%timeit sum(big_array)
%timeit np.sum(big_array)

74.8 ms ± 1.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
980 µs ± 19 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Minimum and Maximum

In [13]:
# python default functions
%timeit min(big_array)
%timeit max(big_array)

50.3 ms ± 794 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
49.1 ms ± 211 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
# Numpy functions
%timeit np.min(big_array)
%timeit np.max(big_array)

404 µs ± 3.15 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
406 µs ± 3.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Multidimensional Aggregates

In [15]:
M = np.random.random((3,4))
M

array([[0.60292266, 0.93224168, 0.04567011, 0.26390403],
       [0.30731841, 0.07349298, 0.93955079, 0.7074469 ],
       [0.76362554, 0.42623636, 0.09619117, 0.50593079]])

In [16]:
# aggregation of entire array
M.sum()

5.664531432917026

In [18]:
# min and max for each col 
M.min(axis=0), M.max(axis=0)

(array([0.30731841, 0.07349298, 0.04567011, 0.26390403]),
 array([0.76362554, 0.93224168, 0.93955079, 0.7074469 ]))