## The key to making a numpy array computation fast is to use vectorized operations

###  These vectorized operations are generally implemented through numpy's universal functions(unfuncs)

In [2]:
import numpy as np

np.random.seed(0)

In [3]:
def compute_reciprocal(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output


In [4]:
values = np.random.randint(1,10,size=5)
compute_reciprocal(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [5]:
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocal(big_array)

1.83 s ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Introduction to UFuncs

In [6]:
print(compute_reciprocal(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [7]:
%timeit (1.0/big_array)

3.21 ms ± 74.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
np.arange(5)/ np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

### Creating the same functions using numpys uFuncs

In [11]:
def compute_reciprocal_ufuncs(values):
    output = np.ones(len(values))
    return np.divide(output,values)

In [12]:
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocal_ufuncs(big_array)

5.7 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Advanced UFunc Features

In [13]:
# If we dont want to create a temp array just for the sake of displaying output 
# then we can use 

# we are ablse to specify where our results of the calculations are to be stored using out variable

x = np.arange(5)
y = np.empty(5)
np.multiply(x,10, out=y)
y


array([ 0., 10., 20., 30., 40.])

In [18]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.random.randint(1,10,(3,3))

array([[5, 9, 5],
       [8, 9, 4],
       [8, 9, 3]])