# Numpy Array Attributes

### Size
### Shape
### Memory Consumption
### Data types of arrays

In [2]:
import numpy as np

np.random.seed(0) # same random arrays are generated each time

In [7]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,3))
x3 = np.random.randint(10,size=(2,2,2))

In [8]:
x1,x2,x3

(array([3, 8, 1, 3, 3, 3]),
 array([[7, 0, 1],
        [9, 9, 0],
        [4, 7, 3]]),
 array([[[2, 7],
         [2, 0]],
 
        [[0, 4],
         [5, 5]]]))

In [10]:
x1.ndim, x2.ndim , x3.ndim

(1, 2, 3)

In [11]:
x1.shape, x2.shape, x3.shape

((6,), (3, 3), (2, 2, 2))

In [13]:
x1.size, x2.size, x3.size

(6, 9, 8)

In [14]:
x1.dtype, x2.dtype, x3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

#  Array Indexing

## Accessing Single Elements

In [16]:
x1[0], x1[-1], x1[2]

(3, 3, 1)

In [22]:
x2[1,1]

9

In [23]:
x3[1,1,1]

5

In [25]:
x3

array([[[2, 7],
        [2, 0]],

       [[0, 4],
        [5, 5]]])

In [26]:
x4 = np.random.randint(10,size=(4,4,4))
x4

array([[[6, 8, 4, 1],
        [4, 9, 8, 1],
        [1, 7, 9, 9],
        [3, 6, 7, 2]],

       [[0, 3, 5, 9],
        [4, 4, 6, 4],
        [4, 3, 4, 4],
        [8, 4, 3, 7]],

       [[5, 5, 0, 1],
        [5, 9, 3, 0],
        [5, 0, 1, 2],
        [4, 2, 0, 3]],

       [[2, 0, 7, 5],
        [9, 0, 2, 7],
        [2, 9, 2, 3],
        [3, 2, 3, 4]]])

In [28]:
x4[1,1]

array([4, 4, 6, 4])

In [30]:
x4[1,2,-1]

4

# Slicing Of Numpy Arrays(Accessing SubArrays)

In [32]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
 x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[:3]

array([0, 1, 2])

In [38]:
x[::2]

array([0, 2, 4, 6, 8])

In [40]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
x[:2]

array([0, 1])

In [43]:
x2

array([[7, 0, 1],
       [9, 9, 0],
       [4, 7, 3]])

## For multiDimensional Arrays

In [45]:
x2[:2,:2] # rows, columns, stepper

array([[7, 0],
       [9, 9]])

### For explicitly copying an array

In [48]:
x2_copy = x2.copy()
x2_copy

array([[7, 0, 1],
       [9, 9, 0],
       [4, 7, 3]])

# Reshaping of Arrays

In [50]:
oneDArr = np.arange(1,10)
oneDArr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
reshapedArr = oneDArr.reshape(3,3)
reshapedArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
oneDArr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# Array Concatenation and Splitting

### Concatenation

In [56]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.concatenate([x,y])
z

array([1, 2, 3, 3, 2, 1])

In [57]:
z1 = np.array([4,5,6]).reshape(3,1)
z1

array([[4],
       [5],
       [6]])

### For tow dimensional arrays concatenation

In [60]:
grid = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([grid,grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate([grid,grid],axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### For working with mixed Dimension

In [64]:
x = np.array([1,2,3])
grid = np.array([
    [9,8,7],
    [6,5,4]
])

# Vertical Stackign
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [66]:
# Horizontal Stacking
y = np.array([
    [99],
    [99]
])
np.hstack([y,grid])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## Splitting of Arrays

### we use functions like : np.split, np.hsplit, np.vsplit

In [68]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
x1,x2,x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [69]:
grid = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11],
    [12,13,14,15]
])

upper,lower = np.vsplit(grid,[2])
upper, lower

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))