In [4]:
import numpy as np

In [3]:
numpy.__version__ 

'1.21.4'

## Creating Arrays from python lists

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

## Creating Arrays from scratch

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0,10,2)

array([ 0., 10.])

In [13]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [14]:
np.full((3,3),12)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [15]:
np.random.random((3,3))

array([[0.33992656, 0.84416655, 0.33706476],
       [0.70633389, 0.06888775, 0.09998549],
       [0.10693463, 0.28198394, 0.37818513]])

In [16]:
np.random.normal(0,1,(3,3))

array([[ 0.28431556,  1.3424021 ,  0.29920303],
       [-0.55373567, -0.12774119,  1.46170952],
       [ 0.44027808,  0.13750955, -1.83419584]])

In [18]:
np.random.randint(0,10,(2,2))

array([[1, 6],
       [7, 4]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])